# Generated by Django 5.1 on 2024-09-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile', models.CharField(max_length=100)),
                ('des', models.TextField(max_length=250)),
                ('instructor', models.CharField(max_length=100)),
                ('duration', models.TimeField()),
            ],
        ),
    ]
