# Generated by Django 5.1 on 2024-09-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_course_model_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_model',
            name='des',
            field=models.CharField(max_length=250),
        ),
    ]
