# Generated by Django 5.1 on 2024-10-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('c_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='images/category')),
            ],
        ),
        migrations.CreateModel(
            name='items',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='images/item')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.category')),
            ],
        ),
    ]
