# Generated by Django 5.1 on 2024-10-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_category_c_id_alter_items_i_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
    ]
