# Generated by Django 5.1 on 2024-10-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_banner_grid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subheading', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('bgcolor', models.TextField(blank=True, null=True)),
                ('btntext', models.TextField(blank=True, null=True)),
                ('btnlink', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='banners/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
