# Generated by Django 5.1 on 2024-10-17 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_items_image'),
        ('design', '0004_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='featured_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.items')),
            ],
        ),
    ]
