# Generated by Django 5.1.1 on 2024-09-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_student_roll_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_model',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
